<a href="https://colab.research.google.com/github/dEROZA/OnlineSubsystemEpic/blob/master/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_1_%7C_%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Лабораторная работа #1 | Основы numpy, pytorch**

> `Сформируем массив numpy, тензор нулевого ранга:`


In [ ]:
import numpy as np
x = np.array(200) 
print(x.ndim)

0


> `Сформируем массив numpy, тензор первого ранга:`

In [ ]:
import numpy as np
y = np.array([1, 2, 3, 4, 5, 6])
print(y.ndim)

1


> `Сформируем массив numpy, тензор второго ранга:`

In [ ]:
import numpy as np
x = np.array([[1, 2, 3], [4,5,6], [4,5,6], [4,5,6]])
print(x.ndim)

2


**Массивы. Основы линейной алгебры**

> *Умножение матрицы на число* - это последовательное умножение каждого элемента матрицы на число.

> *Сложение матриц* - это последовательное сложение элементов каждой из матриц, в случае если размерность матриц совпадает. Для *разности* двух матриц - каждый элемент новой матрицы будет равен поэлементной разности двух других матриц.

`Пример кода умножения матрицы на число и сложения матриц:`




In [ ]:
a = np.eye(3, 4, 0, int)
b = np.eye(3, 4, 1, int)
c = 2*a + b 
print(c)

[[2 1 0 0]
 [0 2 1 0]
 [0 0 2 1]]


**Скалярное произведение векторов**

> *Длинна вектора* равна квадратному корню из суммы квадратов элементов вектора.

> *Скалярное произведение векторов* (а, b), - это число(скаляр) равный сумме произведений поэлементного умножения векторов. Или произведению длин векторов на косинус угла между ними.

`Для реализации скалярного произведения векторов и произведения матриц одинакового размера  используется функция:`

```
# numpy.dot(ar, ar2) или другой формат записи : ar1.dot(ar2)
```

`Пример кода для вычисления скалярного произведения векторов:`

In [ ]:
import numpy as np

A = np.array([1,2,3,4])
B = np.array([0,8,4,0])

print(
    "Даны векторы: А = {} и Б = {}:"
      .format(A, B), "\n"
)
print("Скалярное произведение (формат 1й):", np.dot(A, B))
print("Скалярное произведение (формат 2й):", A.dot(B))

Даны векторы: А = [1 2 3 4] и Б = [0 8 4 0]: 

Скалярное произведение (формат 1й): 28
Скалярное произведение (формат 2й): 28


> *`Чему равно скалярное произведение векторов а = [4, 1, 8] и b = [4, 5, 6]?`*

In [ ]:
import numpy as np

A = np.array([4,1,8])
B = np.array([4,5,6])

print(
    "Даны векторы: А = {} и Б = {}:"
      .format(A, B), "\n"
)
print("Скалярное произведение (формат 1й):", np.dot(A, B))
print("Скалярное произведение (формат 2й):", A.dot(B))

Даны векторы: А = [4 1 8] и Б = [4 5 6]: 

Скалярное произведение (формат 1й): 69
Скалярное произведение (формат 2й): 69


> *Векторное произведение векторов* [AxB], - это вектор равный произведению длин векторов на синус угла между ними.

`В Python для реализации векторного произведения векторов  используется функция numpy.cross(ar1, ar2):`


In [ ]:
import numpy as np

A = np.array([4,1,8])
B = np.array([4,5,6])

print(
    "Даны векторы: А = {} и Б = {}:"
      .format(A, B), "\n"
)
print("Векторное произведение:", np.cross(A, B))
print("Скалярное произведение:", A.dot(B))

Даны векторы: А = [4 1 8] и Б = [4 5 6]: 

Векторное произведение: [-34   8  16]
Скалярное произведение: 69


**Произведение матриц**

> Произведением двух матриц А и В называется матрица С, элемент которой, находящийся на пересечении i-й строки и j-го столбца, равен сумме произведений элементов i-й строки матрицы А на соответствующие (по порядку) элементы j-го столбца матрицы В.

In [ ]:
A = np.array([[1,2], [3,4]])
print( "\nМассив A:\n", A)

B = np.array([[1,2], [3,4]])
print( "\nМассив B:\n", B)

print("\nМассив C:\n", A.dot(B))


Массив A:
 [[1 2]
 [3 4]]

Массив B:
 [[1 2]
 [3 4]]

Массив C:
 [[ 7 10]
 [15 22]]


> Найдите произведение двух матриц.

Первая матрица состоит из единиц, формат массива (5, 3); вторая матрица состоит из семерок, формат массива (3, 2). 

Сделайте вывод каждой матрицы и их произведения.

Для корректной проверки кода, вывод текста и соответствующей ему матрицы реализуйте в  операторе print для каждой матрицы. Для переноса на следующую строку используйте \n.

In [119]:
import numpy as np

A = np.ones((5, 3))
B = np.array([[7,7],[7,7],[7,7]])

print("Массив A:\n", A, "\n")
print("Массив B:\n", B, "\n")
print("Массив C:\n", A.dot(B))

Массив A:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

Массив B:
 [[7 7]
 [7 7]
 [7 7]] 

Массив C:
 [[21. 21.]
 [21. 21.]
 [21. 21.]
 [21. 21.]
 [21. 21.]]


**Базовая работа в PyTorch**

In [ ]:
import torch # создаем экземпляр класса
import random # как же без рандома то?!

rnd = random.randint(0,9)

Создадим наш массив из тензоров 1 порядка, заполненного нулями:

In [ ]:
x = torch.zeros([3,4])

Длаее приводятся базывые операции с тензорами: 

In [124]:
print("size:\n", x.size(), "\n") # размер массива
print("show 2nd stroke of tensor:\n", x[1], "\n") # доступ ко второй строке тензоров массива
print("show 1st element of 1st stroke of tensor:\n", x[0,0], "\n") # формат доступа по типа СТОЛБЕЦ, СТРОКА
print("show 2nd stroke of tensor (slice):\n", x[:1], "\n") # доступ ко второй строке тензора массива
print("add operation on tensors:\n", x+rnd, "\n") # добавляем ко всем элементам массива тензоров скаляр 10
print("add operation on tensor elements:\n", x[1,1]+423423, "\n") # добавляем скаляр 10 к элементу(ам)
print("pow operation tensor^2:\n", (x+10)**2, "\n") # в квадрате, (x+10)**2 не x+10**2, хотя результат будет одинаковый!

size:
 torch.Size([3, 4]) 

show 2nd stroke of tensor:
 tensor([0., 0., 0., 0.]) 

show 1st element of 1st stroke of tensor:
 tensor(0.) 

show 2nd stroke of tensor (slice):
 tensor([[0., 0., 0., 0.]]) 

add operation on tensors:
 tensor([[8., 8., 8., 8.],
        [8., 8., 8., 8.],
        [8., 8., 8., 8.]]) 

add operation on tensor elements:
 tensor(423423.) 

pow operation tensor^2:
 tensor([[100., 100., 100., 100.],
        [100., 100., 100., 100.],
        [100., 100., 100., 100.]]) 



Вопрос: какая операция с тензорами a, b

```
a = torch.ones([5,4])
b = torch.Tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])
```
позволяет получить следующий вывод?
```
tensor([
  [0., 1., 1., 1.],
  [1., 1., 1., 1.],
  [1., 1., 1., 1.],
  [1., 1., 1., 1.],
  [1., 1., 1., 1.]
])
```

Ответ

In [114]:
a = torch.ones([5,4])
b = torch.Tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16], [17,18,19,20]])
print("Оperation a%b:\n", a%b)

Оperation a%b:
 tensor([[0., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Вопрос: какая операция с тензорами a, b:

In [ ]:
a = torch.ones([5,4])
b = torch.Tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16], [17,18,19,20]])

позволяет получить следующий вывод?
```
tensor([2., 3., 4., 5.])
```

In [111]:
print("Оperation b[0]+a[2]:", b[0]+a[2])

Оperation b[0]+a[2]: tensor([2., 3., 4., 5.])


Реализуйте при помощи pyTorch функцию, которая возвращает сумму (x.sum()) элементов тензора X, строго превышающих значение limit, которое является входным значением алгоритма.

In [138]:
X = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Input data:")
mask = X>int(input())
larger_than_limit_sum = X[mask].sum()

print("\nOut sum: {}".format(larger_than_limit_sum))

Input data:
2

Out sum: 42


Что будет в переменной x в результате выполнения следующего кода?


In [141]:
import torch
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = x
y[2] = torch.ones(3)


tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 1, 1]])


```
tensor([
  [1, 2, 3],
  [4, 5, 6],
  [1, 1, 1]
])
```

> **Преобразование numpay array в torch tenzor**

`Переобразуем из int32 в int8`

In [152]:
y = torch.from_numpy(A)
print(y.char())

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int8)
